#!/usr/bin/python3

import sys
import math

def factorize(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = [int(line) for line in file]

    for num in numbers:
        factors = factorize(num)
        p, q = factors[0], factors[1]
        print(f"{num}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    main(file_path)
