#!/usr/bin/python3
from sys import argv
import math

"""Factorize as many numbers as possible into a product of 2 smaller nums"""

def factory(num):
    """Gets the factors of a number.

    Args:
        num (int): The number to factorize.

    Returns:
        tuple: A tuple containing the two factors.
    """
    if num % 2 == 0:
        i = 2
        return int(num//i), i
    else:
        sq = int(math.sqrt(num)) + 1
        for i in range(3, sq, +2):
            if num % i == 0:
                return int(num//i), i
            if num % (sq + i) == 0:
                return sq + i, int(num//(sq + i))
            if num % (sq - i) == 0:
                return sq - i, int(num//(sq - i))

def factors(filename):
    """Reads numbers from a file and prints their factorization."""
    with open(filename, encoding="utf-8") as my_file:
        for line in my_file.readlines():
            n = int(line)
            p, q = factory(n)
            print("{}={}*{}".format(n, p, q))

if __name__ == "__main__":
    factors(argv[1])
