#!/usr/bin/python3
from sys import argv
import math

"""RSA Factoring Challenge"""

def is_prime(num):
    """Check if a number is prime."""
    i = 3
    if num % 2 == 0:
        return False
    while i * i <= num:
        if num % i == 0:
            return False
        i += 2
    return True

def factory(num):
    """Get the first two prime factors of a number and print them out."""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, int(num/i), i))
    else:
        sq = math.sqrt(num)
        if sq % 1 == 0:
            print("{}={}*{}".format(num, int(sq), int(num/sq)))
            return
        sq = int(sq) + 1
        for i in range(3, sq, +2):
            if num % i == 0:
                if is_prime(i):
                    print("{}={}*{}".format(num, int(num/i), i))
                    return

def factors(filename):
    """Read numbers from a file and print their first two prime factors."""
    with open(filename, encoding="utf-8") as my_file:
        for line in my_file.readlines():
            n = int(line)
            factory(n)

if __name__ == "__main__":
    factors(argv[1])
